FROM {{dockerBaseImage}}

WORKDIR /work
RUN microdnf install -y tzdata && microdnf clean all

COPY target/*-runner /work/application

EXPOSE 8080
USER 1001
ENTRYPOINT ["/work/application","-Dquarkus.http.host=0.0.0.0"]

